CREATE PLUGGABLE DATABASE mypdb;
ADMIN USER pdbadmin IDENTIFIED BY patrocl0.$;
FILE_NAME_CONVERT = ('/opt/oracle/oradata/ORCLCDB/', '/opt/oracle/oradata/mypdb/');
ALTER PLUGGABLE DATABASE mypdb OPEN;
ALTER PLUGGABLE DATABASE mypdb SAVE STATE;