version: '3.8'

services:
      # Oracle service (label used to access the service container)
  oracle-xe:

        # Docker Hub image (feel free to change the tag "latest" to any other available one)
    image: gvenzl/oracle-xe:latest

        # Provide passwords and other environment variables to container
    environment:
      ORACLE_RANDOM_PASSWORD: "true"
      APP_USER: fdbadm
      APP_USER_PASSWORD: fqocac21

        # Forward Oracle port
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
        # test: ["CMD", "sqlplus", "-L", "sys/fqocac21c@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always 

volumes:
  oracle-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker_storage/vols/oracle/oradata  # Ruta en el host













