version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      - ORACLE_PWD=fqocac21c
    ports:
      - "1521:1521"  # Mapea el puerto 1521 del host al puerto 1521 del contenedor
    volumes:
      - /mnt/docker_storage/vols/oracle/oradata:/opt/oracle/oradata  # Mapea el directorio del host al contenedor
    restart: always  # Reinicia el contenedor automáticamente si falla
