version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=fqocac21c
    ports:
      - "1521:1521"  # El puerto 1521 del host se vincula al puerto 1521 del contenedor
    volumes:
      - /mnt/docker_storage/vols/oracle/oradata:/opt/oracle/oradata
      - /mnt/docker_storage/vols/oracle/backup:/opt/oracle/backup
    
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM dual;' | sqlplus -L sys/fqocac21c@//localhost:1521/ORCLCDB as sysdba"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always  # Esto asegura que el contenedor se reinicie automáticamente si falla

volumes:
  oracle-data: 
  oracle-backup:
