version: '3.1'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=fqocac21c
    ports:
      - "1521:1521"
    volumes:
      - /mnt/docker_storage/vols/oracle/oradata:/opt/oracle/oradata
      - /mnt/docker_storage/vols/oracle/backup:/opt/oracle/backup
    restart: always

# No es necesario definir volúmenes si estás montando directorios del host
volumes:
  # Si defines volúmenes de Docker, aquí estarían
