version: '3.1'

services:
  oradb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=fqocac21c
    ports:
      - "1521:1521"  # Mapea el puerto 1521 del host al puerto 1521 del contenedor
    volumes:
      - oracle-data:/opt/oracle/oradata  # Asocia el volumen creado
    restart: always  # Reinicia el contenedor si falla

volumes:
  oracle-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/docker_storage/vols/oracle/oradata  # Ruta en el host